### ISSUE TITLE
Blender 4.0 fails to export to X3D when Scene contains lights

### ISSUE THREAD

**Issue by vincentmarchetti** [Web3DConsortium/BlenderX3DSupport#8]
The presence of a PointLight in a Blender scene causes the export script to X3D to fail. This can be demonstrated with the Blender default initial scene, which only contains a cube, a camera, and a point light. Upon invoking the X3D export function the export fails. Below is a terminal log reporting the exception stack trace emitted by the Python script. On first examination the problem seems to be that the Python 'light' instance does not contain a definition for a 'distance' attribute, which the exporter wants to write as the radius attribute of the PointLight element.

This bug was observed in Blender 4.0.2. This bug does not occur in Blender 3.6

This issue does not address whether or not an X3D scene containing a PointLight can be imported into Blender 4.0.2

Info: starting X3D export to '/Users/vmarchetti/Desktop/untitled.x3d'...
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/4.0/scripts/addons/io_scene_x3d/__init__.py", line 224, in execute
    return export_x3d.save(context, **keywords)
  File "/Applications/Blender.app/Contents/Resources/4.0/scripts/addons/io_scene_x3d/export_x3d.py", line 1575, in save
    export(file,
  File "/Applications/Blender.app/Contents/Resources/4.0/scripts/addons/io_scene_x3d/export_x3d.py", line 1508, in export
    export_main()
  File "/Applications/Blender.app/Contents/Resources/4.0/scripts/addons/io_scene_x3d/export_x3d.py", line 1504, in export_main
    export_object(ident, None, obj_main, obj_main_children)
  File "/Applications/Blender.app/Contents/Resources/4.0/scripts/addons/io_scene_x3d/export_x3d.py", line 1446, in export_object
    writePointLight(ident, obj, obj_matrix, data, world)
  File "/Applications/Blender.app/Contents/Resources/4.0/scripts/addons/io_scene_x3d/export_x3d.py", line 482, in writePointLight
    fw(ident_step + 'radius="%.4f" \n' % light.distance)
AttributeError: 'PointLight' object has no attribute 'distance'
Info: starting X3D export to '/Users/vmarchetti/Desktop/untitled2.x3d'...
Info: finished X3D export to '/Users/vmarchetti/Desktop/untitled2.x3d'
Saved session recovery to "/var/folders/b5/rdxvnr2j6tj69lzzl2q38nl40000gn/T/quit.blend"

**Comment by vincentmarchetti** [comment]
Searching the blender source https://github.com/blender/blender shows that a parameter 'distance' was removed from the code in file blender/source/blender/makesrna/intern/rna_light.cc on July 5 2023 ; see commit details at https://github.com/blender/blender/commit/c4ddf169509e44d09f716983f6fe9691d8b939cc

There is also a parameter in the c code call cutoff_distance which appears to play the same role in rendering -- limiting the distance at which the light has influence -- as the X3D field 'radius' in the X3D node PointLight.

Blender lights also has a field 'radius', but in the Blender lighting model the radius of a light refers to the size of a light emitting surface; so a point light is actually a globe light, and the finite size of the lights has the effect of softening the edge of shadows.

**Comment by vincentmarchetti** [comment]
A preliminary fix of the this issue is implemented in the branch x3d-export-light, see commit details https://github.com/Web3DConsortium/BlenderX3DSupport/commit/b80c79c74fa29d63e5bfddf13428cae3f03f49be

The import/export code at this commit sucessfuls exports the Blender initial scene to X3D and successfully re-imports that same scene from X3D.

More detailed testing will be done, in particular plan to create an X3D scene with all of
ambient light
PointLight
SpotLight
DirectionalLight (which in Blender is call SunLight )

and evaluate the round trip X3D -> .blend --> X3D

**Comment by vincentmarchetti** [comment]
The Blender developers have accepted the fix made in https://github.com/Web3DConsortium/BlenderX3DSupport/commit/b80c79c74fa29d63e5bfddf13428cae3f03f49be into the blender/blender-addons project, see (closed) issue https://projects.blender.org/blender/blender-addons/issues/105235

**Comment by vincentmarchetti** [comment]
No further action needed on this issue at this time
